<<<<<<< HEAD
# Generated by Django 3.2.16 on 2023-02-06 07:07
=======
# Generated by Django 4.1 on 2023-01-30 11:17
>>>>>>> 3ed9813b3c5878d7b5d3f7df95dcb9e91e62ae72

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Musique', 'M'), ('Cinema', 'C'), ('Sport', 'S')], max_length=8)),
                ('state', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('nbe_partip', models.IntegerField(default=0)),
=======
                ('nbe_participant', models.IntegerField(default=0)),
>>>>>>> 3ed9813b3c5878d7b5d3f7df95dcb9e91e62ae72
                ('event_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
    ]
