<<<<<<< HEAD
# Generated by Django 3.2.16 on 2023-02-06 07:07
=======
# Generated by Django 4.1 on 2023-01-30 11:17
>>>>>>> 3ed9813b3c5878d7b5d3f7df95dcb9e91e62ae72

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0001_initial'),
<<<<<<< HEAD
=======
        ('Person', '0001_initial'),
>>>>>>> 3ed9813b3c5878d7b5d3f7df95dcb9e91e62ae72
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event_participation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='participation',
            field=models.ManyToManyField(related_name='participations', through='Event.Event_Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='event_participation',
            unique_together={('person', 'event')},
        ),
        migrations.AddConstraint(
            model_name='event',
<<<<<<< HEAD
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 2, 6, 8, 7, 35, 766194))), name='date doit etre > a date systeme'),
=======
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 1, 30, 12, 17, 47, 134236))), name='Date doit être sup à date sys'),
>>>>>>> 3ed9813b3c5878d7b5d3f7df95dcb9e91e62ae72
        ),
    ]
