# Generated by Django 4.1.6 on 2023-02-06 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Date doit être sup à date sys',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 2, 6, 9, 49, 38, 921754))), name='Date doit être sup à date sys'),
        ),
    ]
