# Generated by Django 3.2.16 on 2023-02-06 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_auto_20230206_0951'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='date doit etre > a date systeme',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 2, 6, 9, 52, 23, 845663))), name='date doit etre > a date systeme'),
        ),
    ]
