# Generated by Django 3.2.16 on 2023-02-06 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_auto_20230206_0952'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='date doit etre > a date systeme',
        ),
        migrations.RemoveField(
            model_name='event',
            name='nbe_partip',
        ),
        migrations.AddField(
            model_name='event',
            name='nbe_participant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 2, 6, 10, 14, 34, 400851))), name='Date doit être sup à date sys'),
        ),
    ]
