# Generated by Django 3.2.16 on 2023-02-06 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_auto_20230206_1014'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Date doit être sup à date sys',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 2, 6, 10, 31, 45, 987600))), name='Date doit être sup à date sys'),
        ),
    ]
