# Generated by Django 3.2.16 on 2023-02-06 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_auto_20230206_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Eventss'},
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='Date doit être sup à date sys',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 2, 6, 12, 7, 47, 906532))), name='Date doit être sup à date sys'),
        ),
    ]
